server:
  port: 8086
spring:
  application:
    name: crud-get
  sql:
        init:
            mode: always          # 앱 시작 시 SQL 실행 허용
            encoding: UTF-8
            schema-locations: classpath:schema.sql
            data-locations: classpath:data.sql
